name: timekeeper
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  flutter_login_facebook: ^2.0.1
  provider: ^6.1.2
  cloud_firestore: ^5.4.4
  intl: any
  rxdart: ^0.28.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0

flutter_icons:
    android: true
    ios: true
    image_path: "assets/time.png"

flutter_test:
    sdk: flutter




flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - images/
